name: Trigger Sync on Push

on:
  push:
    branches:
      - master

jobs:
  dispatch-event:
    runs-on: ubuntu-latest

    steps:
      - name: Send Repository Dispatch Event
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TARGET_REPO: "Byte-Your-Dreams/ByteYourDreams.github.io"
          EVENT_TYPE: "sync-folder"

        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
          https://api.github.com/repos/$TARGET_REPO/dispatches \
          -d '{"event_type": "'"$EVENT_TYPE"'"}'